"""initial schema - all models

Revision ID: 505587c356eb
Revises: 
Create Date: 2026-03-26 01:22:39.432629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505587c356eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='매장명. 예: 증산점, 양산점, 범어점',
               existing_comment='매장명. 예: 홍대점, 강남점, 신촌점',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='매장명. 예: 홍대점, 강남점, 신촌점',
               existing_comment='매장명. 예: 증산점, 양산점, 범어점',
               existing_nullable=False)
    # ### end Alembic commands ###
